sudo: required
dist: bionic
language: c
git:
  submodules: true
addons:
  apt:
    packages:
    - autoconf
    - automake
    - autotools-dev
    - build-essential
    - clang
    - cmake
    - gcc
    - jq
    - libglib2.0-dev
    - libtool
    - m4
    - make
    - sudo
    - pkg-config
env:
  matrix:
    - BUILD_TYPE=Debug COMPILER=gcc
    - BUILD_TYPE=Release COMPILER=gcc
    - BUILD_TYPE=Debug COMPILER=clang
    - BUILD_TYPE=Release COMPILER=clang
before_script:
  - mkdir /tmp/oio
  - export NBPROCS=$(nprocs --ignore=1)
  - cd vendor/libdill
  - ./autogen.sh
  - ./configure --prefix=/usr --enable-shared --disable-static --disable-tls --disable-threads
  - make -j ${NBPROCS} all
  - sudo make install
  - cd -
  - export CC=$COMPILER
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=$BUILD_TYPE .
  - make -j ${NBPROC} all
  - sudo make install
script:
  - set -e
  - export TMPDIR=/tmp
  - ./tools/gridinit-genconf.sh 15
  - gridinit -d -s gridinit /tmp/gridinit/gridinit.conf
  - ./tools/cycle.sh
  - pkill gridinit
